# Matrika kanala, marginalne verjetnosti in entropija kanala

In [1]:
import numpy as np
from math import log2

matrix = np.ones([4,4])/16

count = 0

while count < 20:

    row = np.random.randint(matrix.shape[0])
    col = np.random.randint(matrix.shape[1])
    wid = matrix.shape[0]-1
    hei = matrix.shape[1]-1
    a_row = wid-row
    a_col = hei-col
    
    change = round(np.random.rand(),2)
    
    if ((matrix[row][col]+change) <= 1) and ((matrix[a_row][a_col]-change) >= 0):
        matrix[row][col] += change

        matrix[a_row][a_col] -= change
        count += 1

print(matrix)

# Calculate the sum of element*log2(element) for the entire matrix

result_sum = -np.sum(matrix * np.log2(matrix))

# Calculate the sum by rows
p_y = np.sum(matrix,axis=0)
sum_by_rows = -(np.sum(p_y * np.log2(p_y)))

# Calculate the sum by columns
p_X = np.sum(matrix,axis=1)
sum_by_columns = -(np.sum(p_X * np.log2(p_X)))
print("H_xy:", result_sum)
print(f"P_x  {p_X} in H_x: {sum_by_columns}")
print(f"P_y {p_y} in H_y: {sum_by_rows}")

P_k = matrix/p_X[:, np.newaxis]

print(P_k)

[[0.0625 0.0425 0.0225 0.1225]
 [0.1025 0.0925 0.0325 0.0525]
 [0.0725 0.0925 0.0325 0.0225]
 [0.0025 0.1025 0.0825 0.0625]]
H_xy: 3.7576699973737875
P_x  [0.25 0.28 0.22 0.25] in H_x: 1.9947937606110278
P_y [0.24 0.33 0.17 0.26] in H_y: 1.9618321204841158
[[0.25       0.17       0.09       0.49      ]
 [0.36607143 0.33035714 0.11607143 0.1875    ]
 [0.32954545 0.42045455 0.14772727 0.10227273]
 [0.01       0.41       0.33       0.25      ]]


In [2]:
# Create a sample 2D array
array_2d = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])

# Create a sample 1D vector with the same number of values as rows in the array
vector = np.array([2, 3, 4])

# Perform element-wise division
result = array_2d / vector[:, np.newaxis]

# The result will be a new 2D array with each row divided by the corresponding value in the vector
print(result)

[[0.5        1.         1.5       ]
 [1.33333333 1.66666667 2.        ]
 [1.75       2.         2.25      ]]
